### ISSUE TITLE
machine learning project run time errors in azure cloud 

### ISSUE THREAD

**Issue by joepareti54** [Azure/MachineLearningSamples-DeepLearningforPredictiveMaintenance#4]
i am working on the predictive maintenance project in Azure and have the issues described in the attached file: any idea how to deal with those?
[ML experiment in the Azure cloud.pdf](https://github.com/Azure/MachineLearningSamples-DeepLearningforPredictiveMaintenance/files/1671540/ML.experiment.in.the.Azure.cloud.pdf)

**Comment by ehrlinger** [comment]
Thank you for your detailed report. I'll work through your notes and post fixes (hopefully) here. I'll also be working on improving the documentation based on what we find.

**Comment by ehrlinger** [comment]
I think a big part of this problem is the restriction that the free Azure account will not let you provision a DS VM. There is a dependency on a "data science virtual machine" in the Azure Workbench. This gives us a minimal set of installed tools to start the solution from. I do not see the A2m_v2 available under the data science VM provisioning page. This means the docker container will not deploy correctly on that VM platform. 

This is an important restriction, as we have been telling users that the free Azure subscription is an option. I'll dig into this further.

**Comment by ehrlinger** [comment]
That said, if you have a beefy desktop, this scenario could run on a local docker install. My experience is you will need 16G ram or more to get a stable docker install on Windows. This will run a Ubuntu VM on a local docker container.

**Comment by joepareti54** [comment]
thank you so much Sir. I am attaching a zip kit to diagnose the latest attempt. The kit was built as follows:
az ml experiment diagnostics -r jp-project-5_1517304760289 -t fooZZZ
[diagnostics.zip](https://github.com/Azure/MachineLearningSamples-DeepLearningforPredictiveMaintenance/files/1678814/diagnostics.zip)

**Comment by joepareti54** [comment]
sorry I closed by mistake. Case is still open AFAIU

**Comment by ehrlinger** [comment]
I'm going to close this bug report and point you to another project. Your diagnostics indicate that you are concerned about this sample instead. 

https://github.com/Azure/MachineLearningSamples-PredictiveMaintenance

**Comment by joepareti54** [comment]
i have upgraded the msft subscription from free to paid but issues persist:
- I can no longer configure an ubuntu vm (msft support is looking into that)
- the vm I have right now (on paid subscription) runs centos and i canNNOT sudo docker even though I have modified /etc/sudoers

**Comment by ehrlinger** [comment]
You need to provision a Ubuntu DSVM to connect to the workbench. 
Also, the scenario you uploaded is in a different GitHub Repo at 
https://github.com/Azure/MachineLearningSamples-PredictiveMaintenance
